# Generated by Django 5.2.17 on 2026-09-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
